### ISSUE TITLE
Show file meta data in details view

### ISSUE THREAD

**Issue by detj** [leftshifters/clipboard#49]
Show file details like file size in bytes, dimensions in case of image jpg/png

**Comment by detj** [comment]
@sthawali What/How are you showing it?

**Comment by sthawali** [comment]
![screen shot 2015-09-11 at 4 50 45 pm](https://cloud.githubusercontent.com/assets/317513/9813673/55280df4-58a5-11e5-82d5-9855ba07c75e.png)
![screen shot 2015-09-11 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/317513/9813674/5528893c-58a5-11e5-9548-bf58f9276f2a.png)

@detj

**Comment by detj** [comment]
@sthawali okay.

My 2 cents

1. Humanize the size in bytes, i.e. express in MiB, GiB or KiB
2. Change _reps_ to _views_

**Comment by sthawali** [comment]
sure @detj

**Comment by detj** [comment]
:+1:
