### ISSUE TITLE
Master branch has "conflicted" code 

### ISSUE THREAD

**Issue by Aabid-Citrus** [leftshifters/clipboard#59]
https://github.com/leftshifters/clipboard/blob/master/lib/disksize.js

Please resolve and commit this file

**Comment by detj** [comment]
Oh shucks! Sure. We'll fix this.

**Comment by Aabid-Citrus** [comment]
@detj Thanks. Looking forward for it.

Also, can we have a docker image with external config file (if required).. I can see there is an ongoing branch for on this feature. Just want to know when can we expect it

**Comment by detj** [comment]
@Aabid-Citrus Well, Clipboard is open source and it could use some pull requests if they come along. I promise I'll review as soon as possible :)

**Comment by Aabid-Citrus** [comment]
(y)

**Comment by detj** [comment]
33a740b952667afc4bed479c2b2ff0dce259775b
